receivers:
  otlp:
    protocols:
      grpc:

processors:
  groupbytrace:
    wait_duration: 1s
    num_traces: 1_000_000
    num_workers: 100
  batch:
    send_batch_size: 100_000

exporters:
  logging:
    loglevel: debug

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [ pprof, zpages, health_check ]
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ groupbytrace, batch ]
      exporters: [ logging ]
