receivers:
  otlp:
    protocols:
      grpc:
  filelog:
    include: [ /var/log/*.log ]
    operators:
      - type: json_parser
        timestamp:
        parse_from: time
        layout: '%Y-%m-%d %H:%M:%S'

processors:
  correlation_sampling:
    correlation_id: signalgen
    decision_wait: 1s
    num_traces: 1_000_000
    filters:
      [
        {
          name: sample-all,
          type: percentage,
          percentage: { sampling_percentage: 100 }
        },
      ]
  batch:
    send_batch_size: 100_000

exporters:
  logging:
    loglevel: debug

extensions:
  health_check:
  pprof:
  zpages:

service:
  extensions: [ pprof, zpages, health_check ]
  pipelines:
    traces:
      receivers: [ otlp ]
      processors: [ correlation_sampling, batch ]
      exporters: [ logging ]
    logs:
      receivers: [ filelog ]
      processors: [ correlation_sampling, batch ]
      exporters: [ logging ]
